### ISSUE TITLE
Change 4D webserver url port?

### ISSUE THREAD

**Issue by NAMSGithub** [fourctv/JS44D#1]
When I call `call4DRESTMethod()` it defaults to call http://localhost:8080. My webserver is on 8089 because 8080 is in use. Is there an easy way to change this?

I see the variable `fourDUrl` is defined and defaulted to 8080 and the comments say it can be changed, I just can't figure out how. When I install using npm the files/directories in my node_modules are different from the github repository and I don't have the file `src/js44D/JSFourDInterface.ts` to modify the default value. I figure at this point I can chalk it up to being a beginner with this stuff. any help is appreciated.

**Comment by NAMSGithub** [comment]
may be kind of a newbie move but i updated it wherever it occurred in the package folder.
![image](https://user-images.githubusercontent.com/24443636/43742870-196b9eba-9999-11e8-831f-3235e78dd820.png)

**Comment by fourctv** [comment]
You can change the value of the `fourDUrl` variable by using something like this (remember, that variable is static):
```
FourDInterface.fourDUrl = 'http://locahost:8089;
```

You can add that line to your `app.component.ts` **constructor** or **onInit**.

I my `app.component.ts` I usually have code like this:
```
    constructor(...) {
        if (window.location.hostname === 'localhost') { 
            FourDInterface.fourDUrl = 'http://localhost:8080';   
        } else {
            FourDInterface.fourDUrl = window.location.origin;
        }
    }
```

That way, while developing, where the app is being served by node.js, via probably `http://localhost:4200`, I set the URL to access 4D to `localhost:8080` (which you can change to whatever). Then, upon deployment, when the web app will most likely be served by a compiled/built 4D App, you may want to use the base URL used to access your production 4D.

Let me know if that helped.

**Comment by fourctv** [comment]
Now, let me just add that you should not modify anything within your node_modules folder, otw you'd have to repeat it anytime a module gets updated.

**Comment by NAMSGithub** [comment]
Perfect, thank you. It is working for me. Just was missing the idea that I could modify the static variable of the FourDInterface class via `FourDInterface.fourDUrl =`

**Comment by fourctv** [comment]
I also updated the documentation on the wiki page.
